iakunin/codexia-bot

- .circleci/config.yml
- Makefile
- src/main/java/dev/iakunin/codexiabot/codexia/cron/ProjectsHealthCheck.java
- src/main/java/dev/iakunin/codexiabot/github/GithubModule.java
This PR is for https://github.com/iakunin/codexia-bot/issues/8
> 8 - Adding PDD to project

- src/main/java/dev/iakunin/codexiabot/bot/StarsUp.java
- src/test/resources/db-rider/bot/expected/noStarsUpResults_githubRepoWithThreeStats_happyPath.yml
- src/test/resources/db-rider/bot/expected/noStarsUpResults_githubRepoWithTwoStats_happyPath.yml
- src/test/resources/db-rider/bot/expected/oneStarsUpResult_githubRepoWithFourStats_happyPath.yml
- src/test/resources/db-rider/bot/expected/oneStarsUpResult_githubRepoWithThreeStats_happyPath.yml
This PR is for issue https://github.com/iakunin/codexia-bot/issues/28
> #28 - `stars-up`: added a date-time of review creation to review text

- .circleci/config.yml
- src/main/java/dev/iakunin/codexiabot/codexia/cron/ResendErroneousReviews.java
- src/main/java/dev/iakunin/codexiabot/codexia/cron/SendReviews.java
- src/main/java/dev/iakunin/codexiabot/codexia/service/ReviewSender.java
- src/main/java/dev/iakunin/codexiabot/codexia/service/ReviewSenderImpl.java
This pull-request is for issue https://github.com/iakunin/codexia-bot/issues/43
> #43 - Extracting ReviewSender to separate service

- src/main/java/dev/iakunin/codexiabot/bot/Up.java
- src/main/java/dev/iakunin/codexiabot/common/SchedulerConfig.java
- src/main/resources/application.properties
This PR is for issue: https://github.com/iakunin/codexia-bot/issues/48
> #48 - Fixing problem with running multiple crons at the same time

- src/main/java/dev/iakunin/codexiabot/bot/TooManyStars.java
- src/test/resources/db-rider/bot/too-many-stars/expected/noResults_githubRepoWithOneStat_aboveThreshold.yml
- src/test/resources/db-rider/bot/too-many-stars/expected/noResults_githubRepoWithTwoStats_aboveThreshold.yml
This PR is for issue: https://github.com/iakunin/codexia-bot/issues/68
> #68 - TooManyStars: Getting rid of the datetime in review text

- src/main/java/dev/iakunin/codexiabot/codexia/config/ResendReviewsUntilDuplicatedCronConfig.java
- src/main/java/dev/iakunin/codexiabot/codexia/cron/ResendReviewsUntilDuplicated.java
- src/main/java/dev/iakunin/codexiabot/codexia/repository/CodexiaReviewNotificationRepository.java
- src/main/java/dev/iakunin/codexiabot/codexia/sdk/CodexiaClient.java
- src/main/java/dev/iakunin/codexiabot/codexia/service/ReviewSenderImpl.java
- src/main/resources/META-INF/spring-configuration-metadata.json
- src/main/resources/application-prod.properties
- src/test/java/dev/iakunin/codexiabot/codexia/cron/ResendReviewsUntilDuplicatedIntegrationTest.java
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/expected/emptyDatabase.yml
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/expected/happyPath.yml
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/expected/oneSuccessfulNotificationWithDuplicatedCode.yml
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/expected/oneUnsuccessfulNotification.yml
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/initial/emptyDatabase.yml
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/initial/happyPath.yml
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/initial/oneSuccessfulNotificationWithDuplicatedCode.yml
- src/test/resources/db-rider/codexia/cron/resend-reviews-until-duplicated/initial/oneUnsuccessfulNotification.yml
This PR is for issue: https://github.com/iakunin/codexia-bot/issues/85
> #85 - ResendReviewsUntilDuplicated cron + its tests

- src/main/java/dev/iakunin/codexiabot/common/controller/SentryTest.java
This PR is for https://github.com/iakunin/codexia-bot/issues/90
> #90 - Wrapping exception to Runnable in order to get rid of Sonar warning

- src/main/java/dev/iakunin/codexiabot/common/controller/SentryTest.java
This PR is for issue https://github.com/iakunin/codexia-bot/issues/90
> #90 - Sonar warning: throwing dedicated exception instead of a generic one

- src/main/resources/logback-spring.xml
This PR is for https://github.com/iakunin/codexia-bot/issues/113
> #113 - Getting rid of Hypersistence Optimizer logs

- src/main/java/dev/iakunin/codexiabot/codexia/service/ReviewSenderImpl.java
This is for https://github.com/iakunin/codexia-bot/issues/116
> #116 - Getting rid of the deprecated method

- src/main/java/dev/iakunin/codexiabot/bot/Small.java
- src/test/java/dev/iakunin/codexiabot/bot/TooSmallIntegrationTest.java
- src/test/resources/db-rider/bot/too-small/expected/githubLanguageIsNull.yml
- src/test/resources/db-rider/bot/too-small/initial/githubLanguageIsNull.yml
This is for https://github.com/iakunin/codexia-bot/issues/136
> #136 - catching exception

- src/main/java/dev/iakunin/codexiabot/bot/Small.java
- src/main/java/dev/iakunin/codexiabot/bot/toosmall/ExactItem.java
- src/main/java/dev/iakunin/codexiabot/bot/toosmall/FallbackFromNull.java
- src/test/java/dev/iakunin/codexiabot/bot/toosmall/ExactItemTest.java
This is for https://github.com/iakunin/codexia-bot/issues/136
> #136 - ExactItem refactoring to get rid of NullPointerException

- src/main/java/dev/iakunin/codexiabot/bot/toosmall/ExactItem.java
- src/test/java/dev/iakunin/codexiabot/bot/toosmall/ExactItemTest.java
This is for https://github.com/iakunin/codexia-bot/issues/141
> #141 - Handling case when it's `null` instead of items

- src/main/resources/db/changelog/sql/2020-05-02_15:12_github_repo_stat__index.sql
- src/main/resources/db/changelog/sql/2020-05-02_15:50_github_repo_source__index.sql
This is for https://github.com/iakunin/codexia-bot/issues/143
> #143 - Getting rid of slow DB-queries

- src/main/java/dev/iakunin/codexiabot/common/config/feign/Slf4jFeignLogger.java
This is for https://github.com/iakunin/codexia-bot/issues/146
> #146 - Lowering Feign-client log level

- src/main/java/dev/iakunin/codexiabot/codexia/CodexiaModuleImpl.java
- src/main/java/dev/iakunin/codexiabot/codexia/service/Database.java
- src/main/java/dev/iakunin/codexiabot/codexia/service/GithubRepo.java
- src/main/java/dev/iakunin/codexiabot/common/runnable/Logging.java
- src/main/java/dev/iakunin/codexiabot/github/GithubModuleImpl.java
- src/main/java/dev/iakunin/codexiabot/github/cron/stat/LinesOfCode.java
- src/main/java/dev/iakunin/codexiabot/hackernews/HackernewsModuleImpl.java
- src/main/java/dev/iakunin/codexiabot/hackernews/cron/IncrementedParser.java
- src/main/java/dev/iakunin/codexiabot/hackernews/cron/RetryErroneous.java
- src/main/java/dev/iakunin/codexiabot/hackernews/service/Database.java
- src/main/java/dev/iakunin/codexiabot/hackernews/service/GithubRepo.java
- src/main/java/dev/iakunin/codexiabot/reddit/config/Client.java
- src/main/resources/logback-spring.xml
- src/test/java/dev/iakunin/codexiabot/common/runnable/LoggingTest.java
This is for https://github.com/iakunin/codexia-bot/issues/146
> 146 - Getting rid of redundant app-logs 

- Dockerfile-liquibase
- Makefile
- bin/gradle_in_docker.sh
- bin/migrate.sh
- src/main/resources/application-prod.properties
This is for https://github.com/iakunin/codexia-bot/issues/149
> 149 - DB-migrations for prod-env

- src/main/resources/db/changelog/sql/2020-05-03_00:20_github_repo_source__index.sql
This is for https://github.com/iakunin/codexia-bot/issues/143
> #143 - Another db-index

- src/main/java/dev/iakunin/codexiabot/github/entity/GithubRepoStat.java
This is for https://github.com/iakunin/codexia-bot/issues/130
> #130 - Getting rid of this puzzle

- src/main/java/dev/iakunin/codexiabot/bot/Small.java
- src/main/java/dev/iakunin/codexiabot/bot/toosmall/LogNotFound.java
- src/test/java/dev/iakunin/codexiabot/bot/toosmall/LogNotFoundTest.java
This is for https://github.com/iakunin/codexia-bot/issues/135
> #135 - LogNotFound refactoring

- src/main/java/dev/iakunin/codexiabot/bot/toosmall/ExactItem.java
- src/main/java/dev/iakunin/codexiabot/bot/toosmall/LogNotFound.java
- src/test/java/dev/iakunin/codexiabot/bot/toosmall/ExactItemTest.java
- src/test/java/dev/iakunin/codexiabot/bot/toosmall/LogNotFoundTest.java
This is for https://github.com/iakunin/codexia-bot/issues/135
> #135 - ExactItem: added language mapping (Vue -> JavaScript)

- src/main/java/dev/iakunin/codexiabot/bot/toosmall/LogNotFound.java
- src/test/java/dev/iakunin/codexiabot/bot/toosmall/LogNotFoundTest.java
This is for https://github.com/iakunin/codexia-bot/issues/146
> #146 - Lowering log level down to `debug`

- src/main/java/dev/iakunin/codexiabot/CodexiaBotApplication.java
- src/main/java/dev/iakunin/codexiabot/bot/Small.java
- src/main/java/dev/iakunin/codexiabot/bot/config/NotSmallCronConfig.java
- src/main/java/dev/iakunin/codexiabot/bot/config/TooSmallCronConfig.java
- src/test/java/dev/iakunin/codexiabot/bot/SmallTransactionRollbackIntegrationTest.java
- src/test/resources/db-rider/bot/small-transaction-rollback/expected/transactionRollback.yml
- src/test/resources/db-rider/bot/small-transaction-rollback/initial/transactionRollback.yml
This is for https://github.com/iakunin/codexia-bot/issues/134
> #134 - Small bot: test for transaction rollback

- src/main/java/dev/iakunin/codexiabot/hackernews/cron/GapsFiller.java
- src/main/java/dev/iakunin/codexiabot/hackernews/cron/healthcheck/AllItems.java
- src/main/java/dev/iakunin/codexiabot/hackernews/sdk/HackernewsClient.java
- src/main/resources/META-INF/spring-configuration-metadata.json
- src/main/resources/application.properties
- src/test/java/dev/iakunin/codexiabot/hackernews/cron/healthcheck/AllItemsIntegrationTest.java
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/expected/emptyDatabase.yml
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/expected/hackernewsException.yml
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/expected/oneActiveItem.yml
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/expected/oneDeletedItem.yml
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/initial/emptyDatabase.yml
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/initial/hackernewsException.yml
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/initial/oneActiveItem.yml
- src/test/resources/db-rider/hackernews/cron/health-check/all-items/initial/oneDeletedItem.yml
- src/test/resources/wiremock/hackernews/cron/health-check/all-items/oneActiveItem.json
- src/test/resources/wiremock/hackernews/cron/health-check/all-items/oneDeletedItem.json
This is for https://github.com/iakunin/codexia-bot/issues/74
> 74 - AllItemsIntegrationTest

- .circleci/config.yml
- .pdd
- Makefile
This is for https://github.com/iakunin/codexia-bot/issues/37
> #37 - moving PDD config to `.pdd`

- src/main/java/dev/iakunin/codexiabot/hackernews/cron/RetryErroneous.java
- src/test/java/dev/iakunin/codexiabot/hackernews/cron/RetryErroneousIntegrationTest.java
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/expected/emptyDatabase.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/expected/hackernewsException.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/expected/oneItem.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/expected/oneUnprocessedItem.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/expected/twoItems.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/initial/emptyDatabase.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/initial/hackernewsException.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/initial/oneItem.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/initial/oneUnprocessedItem.yml
- src/test/resources/db-rider/hackernews/cron/retry-erroneous/initial/twoItems.yml
- src/test/resources/dbunit.yml
- src/test/resources/wiremock/hackernews/cron/retry-erroneous/1.json
- src/test/resources/wiremock/hackernews/cron/retry-erroneous/2.json
This is for https://github.com/iakunin/codexia-bot/issues/61
> #61 - RetryErroneousIntegrationTest

- README.md
- src/main/java/dev/iakunin/codexiabot/bot/found/Hackernews.java
- src/main/java/dev/iakunin/codexiabot/hackernews/HackernewsModule.java
- src/main/java/dev/iakunin/codexiabot/hackernews/HackernewsModuleImpl.java
- src/main/java/dev/iakunin/codexiabot/hackernews/sdk/HackernewsClient.java
- src/test/java/dev/iakunin/codexiabot/bot/FoundOnHackernewsIntegrationTest.java
- src/test/resources/db-rider/bot/found-on-hackernews/expected/happyPathNoUpvotes.yml
- src/test/resources/wiremock/bot/found-on-hackernews/withScore.json
- src/test/resources/wiremock/bot/found-on-hackernews/withoutScore.json
This is for https://github.com/iakunin/codexia-bot/issues/119
> #119 - FoundOnHackernews: adding upvotes count to review text

- src/main/resources/application-prod.properties
This is for https://github.com/iakunin/codexia-bot/issues/187
> #187 - Running stat.Github cron more seldom

- src/main/java/dev/iakunin/codexiabot/codexia/config/DeleteObsoleteNotificationsCronConfig.java
- src/main/java/dev/iakunin/codexiabot/codexia/cron/DeleteObsoleteNotifications.java
- src/main/java/dev/iakunin/codexiabot/codexia/repository/CodexiaReviewNotificationRepository.java
- src/main/resources/META-INF/spring-configuration-metadata.json
- src/main/resources/application-prod.properties
- src/test/java/dev/iakunin/codexiabot/codexia/cron/DeleteObsoleteNotificationsIntegrationTest.java
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/deletedOneNotificationPerOneReview.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/deletedOneNotificationPerTwoReviews.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/deletedTwoNotificationsPerOneReview.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/deletedTwoNotificationsPerTwoReviews.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/emptyDatabase.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/nothingToDeleteOneReview.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/nothingToDeleteTwoReviews.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/deletedOneNotificationPerOneReview.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/deletedOneNotificationPerTwoReviews.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/deletedTwoNotificationsPerOneReview.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/deletedTwoNotificationsPerTwoReviews.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/emptyDatabase.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/nothingToDeleteOneReview.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/nothingToDeleteTwoReviews.yml
This is for https://github.com/iakunin/codexia-bot/issues/186
> #186 - Deleting obsolete `codexia_review_notification`

- src/main/java/dev/iakunin/codexiabot/codexia/cron/DeleteObsoleteNotifications.java
- src/main/java/dev/iakunin/codexiabot/codexia/repository/CodexiaReviewNotificationRepository.java
- src/main/java/dev/iakunin/codexiabot/codexia/repository/CodexiaReviewRepository.java
- src/main/java/dev/iakunin/codexiabot/hackernews/cron/GapsFiller.java
- src/test/java/dev/iakunin/codexiabot/codexia/cron/DeleteObsoleteNotificationsIntegrationTest.java
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/expected/unableToDelete.yml
- src/test/resources/db-rider/codexia/cron/delete-obsolete-notifications/initial/unableToDelete.yml
This is for https://github.com/iakunin/codexia-bot/issues/186
> #186 - Deleting obsolete `codexia_review_notifications`

- src/main/java/dev/iakunin/codexiabot/github/config/DeleteObsoleteStatCronConfig.java
- src/main/java/dev/iakunin/codexiabot/github/cron/DeleteObsoleteStat.java
- src/main/java/dev/iakunin/codexiabot/github/repository/GithubRepoRepository.java
- src/main/resources/META-INF/spring-configuration-metadata.json
- src/main/resources/application-prod.properties
- src/test/java/dev/iakunin/codexiabot/github/cron/DeleteObsoleteStatIntegrationTest.java
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/emptyDatabase.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/fourStatsOfTwoTypes.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/oneStat.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/sixStatsOfTwoTypes.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/sixStatsOfTwoTypesWithForeignKeys.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/threeStats.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/threeStatsWithForeignKey.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/twoStats.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/expected/twoStatsOfTwoTypes.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/emptyDatabase.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/fourStatsOfTwoTypes.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/oneStat.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/sixStatsOfTwoTypes.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/sixStatsOfTwoTypesWithForeignKeys.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/threeStats.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/threeStatsWithForeignKey.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/twoStats.yml
- src/test/resources/db-rider/github/cron/delete-obsolete-stat/initial/twoStatsOfTwoTypes.yml
This is for https://github.com/iakunin/codexia-bot/issues/190
> #190 - Deleting obsolete `github_repo_stat

- README.md
- src/main/java/dev/iakunin/codexiabot/codexia/cron/MissingFiller.java
- src/main/java/dev/iakunin/codexiabot/codexia/repository/CodexiaProjectRepository.java
- src/test/java/dev/iakunin/codexiabot/codexia/cron/MissingFillerIntegrationTest.java
- src/test/java/dev/iakunin/codexiabot/codexia/repository/CodexiaProjectRepositoryIntegrationTest.java
- src/test/resources/db-rider/codexia/cron/missing-filler/expected/oneDeletedWithoutGithubRepo.yml
- src/test/resources/db-rider/codexia/cron/missing-filler/initial/oneDeletedWithoutGithubRepo.yml
This is for https://github.com/iakunin/codexia-bot/issues/214
> #214 - Deleted codexia-projects should be excluded from checks

- src/main/java/dev/iakunin/codexiabot/github/cron/DeleteObsoleteStat.java
- src/main/java/dev/iakunin/codexiabot/github/repository/GithubRepoRepository.java
This is for https://github.com/iakunin/codexia-bot/issues/190
> #190 - Using paging for DeleteObsoleteStat

- README.md
- bin/create_tag.sh
- src/main/java/dev/iakunin/codexiabot/codexia/README.md
- src/main/java/dev/iakunin/codexiabot/github/service/GithubRepoName.java
- src/main/java/dev/iakunin/codexiabot/github/service/LinesOfCodeImpl.java
- src/main/java/dev/iakunin/codexiabot/hackernews/README.md
- src/test/java/dev/iakunin/codexiabot/codexia/cron/DeleteObsoleteNotificationsIntegrationTest.java
- src/test/java/dev/iakunin/codexiabot/dbunit/CustomPostgresqlDataTypeFactory.java
This is for https://github.com/iakunin/codexia-bot/issues/88
> #88 - Codaxy fixes

- README.md
This is for https://github.com/iakunin/codexia-bot/issues/12
> #12 - Better code hub

- src/test/resources/db-rider/bot/not-small/initial/happyPath.yml
- src/test/resources/db-rider/bot/not-small/initial/linesOfCodeLessThanThreshold.yml
- src/test/resources/db-rider/bot/not-small/initial/resultWithTypeReset.yml
- src/test/resources/db-rider/bot/too-small-transaction/initial/transactionRollback.yml
- src/test/resources/db-rider/bot/too-small/initial/githubLanguageIsNull.yml
- src/test/resources/db-rider/bot/too-small/initial/githubStatIsAbsent.yml
- src/test/resources/db-rider/bot/too-small/initial/happyPath.yml
- src/test/resources/db-rider/bot/too-small/initial/linesOfCodeIsAbsent.yml
- src/test/resources/db-rider/bot/too-small/initial/moreThanThreshold.yml
- src/test/resources/db-rider/bot/too-small/initial/oneResetResult.yml
- src/test/resources/db-rider/bot/too-small/initial/oneSetResult.yml
This is for https://github.com/iakunin/codexia-bot/issues/5
> #5 - Getting rid of the wrong json

- .codeclimate.yml
- .github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/iakunin/codexia-bot/issues/78
> #78 - pull request template
